### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [yagihashib/tc359week2project3#1]
It looks like I'm getting some [HTML errors for Heroku app](http://validator.w3.org/check?uri=http%3A%2F%2Fweek2by.herokuapp.com%2F&charset=%28detect+automatically%29&doctype=Inline&group=0). Can you try fixing these and update GitHub and Heroku?

**Comment by yagihashib** [comment]
Sorry Chris, I forgot to put it through validation. I'm fixing those errors
right now and will have the new version up ASAP.

**Comment by yagihashib** [comment]
I've just uploaded a fixed version on Heroku and Git, sorry for the late
response!

**Comment by chrisvfritz** [comment]
:+1: Looks good. This isn't something you have to fix in this project, but in the future, I'd like to see more descriptive commit messages. The `r{1-n}` pattern doesn't tell me what changes you made and that can be very useful when you need to revert or figure out where a problem started.
